// Generated by CoffeeScript 1.4.0

/*
* Knockout Hammer
* knockout (https://github.com/SteveSanderson/knockout)
* hammer.js (https://github.com/EightMedia/hammer.js)
* Usage: data-bind="hmHold: holdHandlerFn, hmOptions: { hold_timeout: 400 }"
* http://jsfiddle.net/9AA7U/1/
*/


(function() {

  ['hold', 'tap', 'doubletap', 'drag', 'dragstart', 'dragend', 'dragup', 'dragdown', 'dragleft', 'dragright', 'swipe', 'swipeup', 'swipedown', 'swipeleft', 'swiperight', 'transform', 'transformstart', 'transformend', 'rotate', 'pinch', 'pinchin', 'pinchout', 'touch', 'release'].forEach(function(gesture) {
    return ko.bindingHandlers["hm" + (gesture[0].toUpperCase()) + (gesture.slice(1).toLowerCase())] = {
      init: function(element, valueAccessor, allBindingsAccessor, data) {
          console.log("hallo");
        var handler, options, _ref;
        if (!valueAccessor()) {
          return false;
        }
          console.log("2");
        options = allBindingsAccessor().hmOptions || {};
          console.log("3");
        handler = valueAccessor().bind(data);
          console.log("4 "+handler);
        if ((_ref = data.hammer) == null) {
          data.hammer = Hammer(element, options);
          console.log("6 "+hammer);
        }
        data.hammer.on(gesture, handler);
          console.log("7 "+gesture);
        ko.utils.domNodeDisposal.addDisposeCallback(element, function() {
          return data.hammer.off(gesture, handler);
        });
        return true;
      }
    };
  });

}).call(this);
